#!/bin/sh

. ./config

echo making $TAR
rm -f $TAR
tar vcf $TAR --exclude 'bospre-*-fs' \
             --exclude 'bospre-*.img' \
             --exclude 'initrd' \
             --exclude '*.tar' \
             --exclude mnt .
ls -l $TAR
