#!/bin/sh
#
# Send email to the judge.
#
# File:		hpcm_sendmail
# Author:	Bob Walton <walton@deas.harvard.edu>
# Date:		Wed Sep 12 13:25:01 EDT 2001
#
# The authors have placed this program in the public
# domain; they make no warranty and accept no liability
# for this program.
#
# RCS Info (may not be true date or author):
#
#   $Author: hc3 $
#   $Date: 2001/09/12 17:23:47 $
#   $RCSfile: hpcm_sendmail,v $
#   $Revision: 1.5 $

case "$1" in
     "")
    		;;
     *)
    		echo "
cat email_file | hpcm_sendmail

    Sends the email in the email_file to the judge.
    Similar to sendmail -oi -t but adds its own \`To:'
    field, which should not be included in the email_
    file.
	
    The mail is sent to the address in the first read-
    able .HPCM_ADDRESS file found by searching the
    current directory and its ancestors, and the mail is
    cc'ed to the sending user account."

		exit 1
		;;
esac

if test -x /usr/sbin/sendmail
then
    sendmail=/usr/sbin/sendmail
elif test -x /sbin/sendmail
then
    sendmail=/sbin/sendmail
elif test -x /usr/bin/sendmail
then
    sendmail=/usr/bin/sendmail
elif test -x /bin/sendmail
then
    sendmail=/bin/sendmail
elif test -x /usr/lib/sendmail
then
    sendmail=/usr/lib/sendmail
elif test -x /lib/sendmail
then
    sendmail=/lib/sendmail
else
    echo Cannot find sendmail program
    exit 1
fi

# Look for .HPCM_ADDRESS file.
#
if test -r .HPCM_ADDRESS
then
    address=`cat .HPCM_ADDRESS`
elif test -r ../.HPCM_ADDRESS
then
    address=`cat ../.HPCM_ADDRESS`
elif test -r ../../.HPCM_ADDRESS
then
    address=`cat ../../.HPCM_ADDRESS`
elif test -r ../../../.HPCM_ADDRESS
then
    address=`cat ../../../.HPCM_ADDRESS`
else
    echo "ERROR: Cannot find .HPCM_ADDRESS file"
    exit 1
fi

# Submit program file by email.
#
( echo To: "$address"; \
  echo Cc: `id -un`; \
  cat - )                | $sendmail -oi -t

exit 0
