#!/bin/sh -f
#
# Submit a file.
#
# File:		hpcm_submit
# Author:	Bob Walton <walton@deas.harvard.edu>
# Date:		Fri Sep  1 08:38:46 EDT 2000
#
# The authors have placed this program in the public
# domain; they make no warranty and accept no liability
# for this program.
#
# RCS Info (may not be true date or author):
#
#   $Author: acm-cont $
#   $Date: 2000/09/06 21:23:37 $
#   $RCSfile: hpcm_submit,v $
#   $Revision: 1.3 $

case "$1" in
    "" | -*)
    		echo hi
		exit 1
		;;
esac

program=""
extras=""
for e in .c .cc .java .p; do
    if test -r $1$e; then
        if test "$program" = ""; then
	    program=$1$e
	else
	    extras="$extras $1$e"
	fi
    fi
done

if test "$program" = ""; then
    echo "ERROR: no files to submit"
    exit 1
elif test "$extras" != ""; then
    echo "ERROR: too many files to submit:"
    echo "       $program$extras"
    exit 1
fi

( echo BEGIN $program; \
  cat $program | sed -e '/^/s//../'; \
  echo END $program ) \
| mail -s "submit $program" '"HC3 Practice" <walton>' $USER
