#!/bin/sh -f
#
# Submit a file.
#
# File:		hpcm_submit
# Author:	Bob Walton <walton@deas.harvard.edu>
# Date:		Sat Sep  9 15:48:26 EDT 2000
#
# The authors have placed this program in the public
# domain; they make no warranty and accept no liability
# for this program.
#
# RCS Info (may not be true date or author):
#
#   $Author: acm-cont $
#   $Date: 2000/09/09 20:11:09 $
#   $RCSfile: hpcm_submit,v $
#   $Revision: 1.4 $

# If you have a linux system you can symbolically
# link this to ~/bin/hpcm_submit and use the problem
# Makefiles.

case "$1" in
    "" | -*)
    		echo "
hpcm_submit program

	Submits program to email address named in
	the environment variable HPCM_SUBMIT_ADDRESS.
	The program is given without extension, e.g.,
	without .c or .cc: the extension is added and
	the program source is submitted by email."

		exit 1
		;;
esac

program=""
extras=""
for e in .c .cc .java .p; do
    if test -r $1$e; then
        if test "$program" = ""; then
	    program=$1$e
	else
	    extras="$extras $1$e"
	fi
    fi
done

if test "$program" = ""; then
    echo "ERROR: no files to submit"
    exit 1
elif test "$extras" != ""; then
    echo "ERROR: too many files to submit:"
    echo "       $program$extras"
    exit 1
fi

( echo BEGIN $program; \
  cat $program | sed -e '/^/s//../'; \
  echo END $program ) \
| mail -s "submit $program" $HPCM_SUBMIT_ADDRESS $USER
