#!/bin/sh
#
# Submit a file.
#
# File:		hpcm_submit
# Author:	Bob Walton <walton@deas.harvard.edu>
# Date:		Thu Nov  9 00:12:10 EST 2000
#
# The authors have placed this program in the public
# domain; they make no warranty and accept no liability
# for this program.
#
# RCS Info (may not be true date or author):
#
#   $Author: hc3 $
#   $Date: 2000/11/09 05:10:08 $
#   $RCSfile: hpcm_submit,v $
#   $Revision: 1.10 $

case "$1" in
    "" | -*)
    		echo "
hpcm_submit program

	Submits the program to the email address named
	in the environment variable HPCM_ADDRESS.  The
	program is given without extension, e.g., with-
	out .c or .cc: the extension is added automa-
	tically and the program source is submitted by
	email."

		exit 1
		;;
esac

# Locate the program file name, with extension.  If
# there is more than one, determine a list of extras.
#
program=""
extras=""
for e in .c .cc .java .p; do
    if test -r $1$e; then
        if test "$program" = ""; then
	    program=$1$e
	else
	    extras="$extras $1$e"
	fi
    fi
done

# Complain if there is not exactly one program file
# with extension.
#
if test "$program" = ""; then
    echo "ERROR: no files to submit"
    exit 1
elif test "$extras" != ""; then
    echo "ERROR: too many files to submit:"
    echo "       $program$extras"
    exit 1
fi

# Submit program file by email.
#
( echo "Subject: submit $program"; \
  echo ""; \
  echo HPCM_BEGIN $program; \
  cat $program | sed -e '/^/s//../'; \
  echo HPCM_END $program ) \
| hpcm_sendmail
