# HPCM Contestant Help Email Sh Directory Makefile
#
# File:		Makefile
# Authors:	Bob Walton (walton@deas.harvard.edu)
# Date:		Tue Nov  7 23:58:03 EST 2000
#
# The authors have placed this program in the public
# domain; they make no warranty and accept no liability
# for this program.
#
# RCS Info (may not be true date or author):
#
#   $Author: hc3 $
#   $Date: 2000/11/08 05:38:19 $
#   $RCSfile: Makefile,v $
#   $Revision: 1.2 $

all:	hpcm_extract

# Kill all implicit rules
#
.SUFFIXES:

hpcm_extract:
	ln -s ../../../bin/hpcm_extract .

clean:
