# HPCM Contestant Help Directory Makefile
#
# File:		Makefile
# Authors:	Bob Walton (walton@deas.harvard.edu)
# Date:		Wed Nov  1 05:56:58 EST 2000
#
# The authors have placed this program in the public
# domain; they make no warranty and accept no liability
# for this program.
#
# RCS Info (may not be true date or author):
#
#   $Author: hc3 $
#   $Date: 2000/11/01 10:59:50 $
#   $RCSfile: Makefile,v $
#   $Revision: 1.1 $

all:	hpcm_extract

# Kill all implicit rules
#
.SUFFIXES:

hpcm_extract:
	ln -s ../../../bin/hpcm_extract .

clean:
